steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_CR_SERVICE_NAME:latest
      - .
    id: Build docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_CR_SERVICE_NAME:latest
    id: Push docker image  
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY